//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

namespace AssemblyCSharp
{
	public class Grid : IWorld
	{
		public float step = 2.0f;

		public Grid ()
		{
			
		}

		public void Destroy ()
		{

		}

		public Graph Create (GameSystemSettings gss)
		{
			//float x = gss.width  / 2.0f;
			//float y = gss.height / 2.0f;
			//float z = gss.depth  / 2.0f;

			float x, y, z = 0.0f;
			
			Debug.Log ("Creating World:");
			Debug.Log ("Start...X=" + x + " Y=" + y + " Z=" + z); 
			
			for (int i = 0; i < gss.width; i++, x+=step) 
			{
				for(int j = 0; j < gss.depth; j++, z+=step)
				{
					for(int k = 0; k < gss.height; k++, y+=step)
					{

					}
				}
			}


		}
	}
}

