//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Graph : IGraph
	{
		bool _directed = false;

		public Graph (bool directed)
		{
			_directed = directed;
		}

		public void addVertex (UnityEngine.GameObject go)
		{
			throw new NotImplementedException ();
		}

		public void removeVertex (UnityEngine.GameObject go)
		{
			throw new NotImplementedException ();
		}

		public void addEdge (UnityEngine.GameObject go1, UnityEngine.GameObject go2)
		{
			throw new NotImplementedException ();
		}

		public void removeEdge (UnityEngine.GameObject go1, UnityEngine.GameObject go2)
		{
			throw new NotImplementedException ();
		}

		public System.Collections.Generic.List<UnityEngine.GameObject> getEdge (UnityEngine.GameObject go)
		{
			throw new NotImplementedException ();
		}

		public int size ()
		{
			throw new NotImplementedException ();
		}

		public bool isEmpty ()
		{
			throw new NotImplementedException ();
		}
	}
}

